# Generated by Django 5.1 on 2024-10-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='user',
            field=models.CharField(default='default_user', max_length=50, unique=True),
        ),
    ]
