# Generated by Django 5.1 on 2024-11-03 23:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporarySpotifyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_songs', models.JSONField(blank=True, default=list)),
                ('top_artists_with_images', models.JSONField(blank=True, default=list)),
                ('vibe_data', models.JSONField(blank=True, default=dict)),
                ('genre_data', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='spotifyprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spotifyprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spotify_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
