# Generated by Django 5.1.1 on 2024-11-03 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifyprofile',
            old_name='top_artists_with_images',
            new_name='top_five_artists',
        ),
    ]
