# Generated by Django 5.1 on 2024-11-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0002_temporaryspotifyprofile_spotifyprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryspotifyprofile',
            name='vibe_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
