# Generated by Django 5.1 on 2024-11-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0003_alter_temporaryspotifyprofile_vibe_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifyprofile',
            old_name='top_artists_with_images',
            new_name='top_five_artists',
        ),
        migrations.RenameField(
            model_name='temporaryspotifyprofile',
            old_name='top_artists_with_images',
            new_name='top_five_artists',
        ),
        migrations.AddField(
            model_name='spotifyprofile',
            name='top_five_songs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='temporaryspotifyprofile',
            name='top_five_songs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='spotifyprofile',
            name='vibe_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
