name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
#    - name: Run Tests
#      run: |
#        python manage.py test
    - name: Analyzing code with pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: Run tests with coverage
      run: |
        pytest tests/ --cov=spotifywrapped --cov-report=xml

    - name: Verify code coverage
      run: |
        coverage=$(grep 'line-rate' coverage.xml | sed -E 's/.*line-rate="([^"]+)".*/\1/')
        coverage=$(echo "$coverage * 100" | bc)
        echo "Coverage: $coverage%"
        if (( $(echo "$coverage < 80" | bc -l) )); then
          echo "Code coverage ($coverage%) is below 80%! Failing the build."
          exit 1
        fi
